{
 "title": "MLOps Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Predictions Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rice_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model F1 Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_f1_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model AUC-PR",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_auc_pr", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Mean Recall",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_mean_recall", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Metrics Evolution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "model_f1_score", "legendFormat": "F1 Score" },
    { "expr": "model_auc_pr", "legendFormat": "AUC-PR" },
    { "expr": "model_mean_recall", "legendFormat": "Mean Recall" }
   ]
  },
  {
   "title": "Active Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_model_info == 1", "legendFormat": "{{model_name}}" }
   ]
  }
 ]
}